import assert from "node:assert/strict"
import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"
import test from "node:test"

const projectRoot = join(import.meta.dirname, "../../")

function readProjectFile(path) {
  return readFileSync(join(projectRoot, path), "utf-8")
}

test("roster change governance route now presents the todo workbench", () => {
  const pagePath = join(projectRoot, "app/roster-change-governance/page.tsx")

  assert.ok(existsSync(pagePath), "app/roster-change-governance/page.tsx must exist")

  const content = readFileSync(pagePath, "utf-8")
  assert.ok(content.includes("RosterChangeGovernanceWorkbench"))
  assert.ok(content.includes("generateRosterDraftViewModel"))
  assert.ok(content.includes('title="待办"'))
  assert.ok(content.includes('breadcrumbItems={[{ label: "待办" }]}'))
  assert.ok(content.includes("initialCellId"))
  assert.ok(content.includes("initialIssueId"))
  assert.ok(content.includes("h-[calc(100svh-var(--header-height))]"))
  assert.ok(!content.includes("班务变更申请"))
  assert.ok(!content.includes("班务申请中心"))
  assert.ok(!content.includes("正式班表变更治理"))
  assert.ok(!content.includes("班表变更中心"))
})

test("todo workbench uses request-first states and actions", () => {
  const content = readProjectFile("components/roster-change-governance-workbench.tsx")

  assert.ok(content.includes('"use client"'))
  assert.ok(content.includes('data-slot="duty-change-request-shell"'))
  assert.ok(content.includes('data-slot="duty-change-request-tabs"'))
  assert.ok(content.includes('data-slot="duty-change-adjustment-layout"'))
  assert.ok(content.includes('data-slot="duty-change-request-queue"'))
  assert.ok(content.includes('data-slot="duty-change-current-cell-adjustment"'))
  assert.ok(content.includes('data-slot="duty-change-handling-panel"'))
  assert.ok(content.includes('className="min-h-0 flex-1 flex-col gap-0"'))
  assert.ok(content.includes('data-slot="duty-change-request-list"'))
  assert.ok(content.includes("待办"))
  assert.ok(content.includes("班务申请"))
  assert.ok(content.includes("待处理"))
  assert.ok(content.includes("跟进中"))
  assert.ok(content.includes("已处理"))
  assert.ok(content.includes("按员工"))
  assert.ok(content.includes("同意"))
  assert.ok(content.includes("拒绝"))
  assert.ok(content.includes("跟进"))
  assert.ok(content.includes("去调整班表"))
  assert.ok(content.includes("保存调整"))
  assert.ok(content.includes("返回申请"))
  assert.ok(content.includes("处理下一条"))
  assert.ok(content.includes("调整为"))
  assert.ok(content.includes("轻量影响提示"))
  assert.ok(content.includes("只调整当前员工/日期格"))
  assert.ok(content.includes("selectNextPendingRequest"))
  assert.ok(content.includes("/api/v1/roster-requests"))
  assert.ok(content.includes("/api/v1/roster-drafts/current-published"))
  assert.ok(content.includes("/api/v1/roster-drafts/revisions/create"))
  assert.ok(content.includes("/api/v1/roster-drafts/publish"))
  assert.ok(content.includes("/follow-up"))
  assert.ok(content.includes("/resolve"))
  assert.ok(content.includes("/close"))
  assert.ok(content.includes("linked_revision_version_id"))
  assert.ok(content.includes("已调整"))
  assert.ok(content.includes("已拒绝"))
  assert.ok(content.includes("已关闭"))
  assert.ok(!content.includes("班务变更申请"))
  assert.ok(!content.includes("班务申请中心"))
  assert.ok(!content.includes("initialRequests"))
  assert.ok(!content.includes("已完成班表调整"))
  assert.ok(!content.includes("确认变更"))
  assert.ok(!content.includes("全部变更"))
  assert.ok(!content.includes("修订前"))
  assert.ok(!content.includes("修订后"))
  assert.ok(!content.includes('data-slot="duty-change-request-detail-drawer"'))
  assert.ok(!content.includes("打开月班表调整页"))
  assert.ok(!content.includes("/api/v1/roster-change-governance/events/"))
  assert.ok(!content.includes("版本时间线"))
  assert.ok(!content.includes("人员-日期差异"))
  assert.ok(!content.includes("source_cell_id"))
  assert.ok(!content.includes("diff"))
  assert.ok(!content.includes("审批状态"))
  assert.ok(!content.includes("批量导出"))
})

test("duty change request route is owned by the slim task sidebar entry", () => {
  const content = readProjectFile("components/app-sidebar.tsx")

  assert.ok(content.includes('title: "待办"'))
  assert.ok(content.includes("/roster-change-governance"))
  assert.ok(content.includes("/duty-requests"))
  assert.ok(content.includes("/published-roster"))
  assert.ok(content.includes("/roster-drafts"))
  assert.ok(!content.includes('title: "班务变更申请"'))
  assert.ok(!content.includes("正式班表变更治理"))
  assert.ok(!content.includes("班表变更中心"))
})
