import type { RosterDraftFixture } from "@/lib/roster-drafts"

export const rosterDraftDemoFixture: RosterDraftFixture = {
  project: {
    projectId: "BOSCH-CS",
    projectName: "博世客服项目",
    workplaceName: "上海职场",
  },
  targetMonths: ["2026-08", "2026-09"],
  shiftTypes: [
    {
      shiftCode: "A2",
      label: "早班",
      intervalLabel: "07:30-12:30",
      stableForCopy: true,
    },
    {
      shiftCode: "A5",
      label: "白班",
      intervalLabel: "09:00-14:30",
      stableForCopy: true,
    },
    {
      shiftCode: "A10",
      label: "晚白班",
      intervalLabel: "14:30-20:00",
      stableForCopy: true,
    },
    {
      shiftCode: "N",
      label: "夜班",
      intervalLabel: "20:00-08:00",
      stableForCopy: true,
    },
    {
      shiftCode: "REST",
      label: "休",
      intervalLabel: "休息",
      stableForCopy: true,
    },
  ],
  employees: [
    {
      employeeId: "EMP-001",
      employeeName: "Alice Chen",
      teamId: "G1",
      teamName: "G1 投诉组",
      active: true,
    },
    {
      employeeId: "EMP-002",
      employeeName: "Ben Wang",
      teamId: "G1",
      teamName: "G1 投诉组",
      active: true,
    },
    {
      employeeId: "EMP-003",
      employeeName: "Cathy Li",
      teamId: "G2",
      teamName: "G2 在线组",
      active: true,
    },
    {
      employeeId: "EMP-004",
      employeeName: "Derek Zhou",
      teamId: "G2",
      teamName: "G2 在线组",
      active: true,
    },
    {
      employeeId: "EMP-005",
      employeeName: "Evan Xu",
      teamId: "G2",
      teamName: "G2 在线组",
      active: true,
      previousTeamId: "G1",
    },
    {
      employeeId: "EMP-006",
      employeeName: "Fiona Sun",
      teamId: "G2",
      teamName: "G2 在线组",
      active: true,
      hireMonth: "2026-08",
    },
  ],
  sourceAssignments: [
    {
      assignmentId: "SRC-001-0727",
      employeeId: "EMP-001",
      businessDate: "2026-07-27",
      assignmentKind: "shift",
      shiftCode: "A5",
      stableForCopy: true,
    },
    {
      assignmentId: "SRC-001-0728",
      employeeId: "EMP-001",
      businessDate: "2026-07-28",
      assignmentKind: "shift",
      shiftCode: "A5",
      stableForCopy: true,
    },
    {
      assignmentId: "SRC-001-0728-MEETING",
      employeeId: "EMP-001",
      businessDate: "2026-07-28",
      assignmentKind: "meeting",
      annotationCode: "TEAM-MEETING",
      intervalLabel: "15:00-16:00",
      stableForCopy: false,
      note: "小组会只记录，不复制成下月班种",
    },
    {
      assignmentId: "SRC-001-0729",
      employeeId: "EMP-001",
      businessDate: "2026-07-29",
      assignmentKind: "shift",
      shiftCode: "A10",
      stableForCopy: true,
    },
    {
      assignmentId: "SRC-001-0730",
      employeeId: "EMP-001",
      businessDate: "2026-07-30",
      assignmentKind: "shift",
      shiftCode: "A10",
      stableForCopy: true,
    },
    {
      assignmentId: "SRC-001-0731",
      employeeId: "EMP-001",
      businessDate: "2026-07-31",
      assignmentKind: "shift",
      shiftCode: "A5",
      stableForCopy: true,
    },
    {
      assignmentId: "SRC-002-0727",
      employeeId: "EMP-002",
      businessDate: "2026-07-27",
      assignmentKind: "shift",
      shiftCode: "A2",
      stableForCopy: true,
    },
    {
      assignmentId: "SRC-002-0728",
      employeeId: "EMP-002",
      businessDate: "2026-07-28",
      assignmentKind: "shift",
      shiftCode: "A2",
      stableForCopy: true,
    },
    {
      assignmentId: "SRC-002-0729",
      employeeId: "EMP-002",
      businessDate: "2026-07-29",
      assignmentKind: "shift",
      shiftCode: "BAD-X",
      stableForCopy: true,
    },
    {
      assignmentId: "SRC-002-0730",
      employeeId: "EMP-002",
      businessDate: "2026-07-30",
      assignmentKind: "shift",
      shiftCode: "A10",
      stableForCopy: true,
    },
    {
      assignmentId: "SRC-002-0731",
      employeeId: "EMP-002",
      businessDate: "2026-07-31",
      assignmentKind: "shift",
      shiftCode: "REST",
      stableForCopy: true,
    },
    {
      assignmentId: "SRC-003-0727",
      employeeId: "EMP-003",
      businessDate: "2026-07-27",
      assignmentKind: "shift",
      shiftCode: "N",
      stableForCopy: true,
    },
    {
      assignmentId: "SRC-003-0728",
      employeeId: "EMP-003",
      businessDate: "2026-07-28",
      assignmentKind: "shift",
      shiftCode: "N",
      stableForCopy: true,
    },
    {
      assignmentId: "SRC-003-0729",
      employeeId: "EMP-003",
      businessDate: "2026-07-29",
      assignmentKind: "annotation",
      annotationCode: "MENTOR",
      stableForCopy: false,
      note: "带教备注不复制成班种",
    },
    {
      assignmentId: "SRC-005-0727",
      employeeId: "EMP-005",
      businessDate: "2026-07-27",
      assignmentKind: "shift",
      shiftCode: "A5",
      teamId: "G1",
      stableForCopy: true,
    },
  ],
}
